<h1>Data Preprocessing Template</h1>

<h3>This notebook focuses on data preprocessing and aims to create a template for further use in the course</h3>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataFilePath = '../../data/Part 1 - Data Preprocessing/Data.csv'

<h3>Importing and visualizing the dataset</h3>

In [2]:
dataset = pd.read_csv(dataFilePath)
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

<h3>Creating independent variable and dependent variable arrays</h3>

In [3]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

<h3>Handling missing data</h3>

<h4>Missing data will be replaced by a mean of all avaible values</h4>

In [4]:
from sklearn.preprocessing import Imputer

imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

<h3>Encoding categorical data</h3>

<h4>Categorical data will be encoded in to values</h4>
<h4>Country data will be encoded in to dummy variables</h4>
<h4>Purchased data will be encoded in to simple values</h4>

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

xLabelEncoder = LabelEncoder()
X[:, 0] = xLabelEncoder.fit_transform(X[:, 0])
oneHotEncoder = OneHotEncoder(categorical_features = [0])
X = oneHotEncoder.fit_transform(X).toarray()

yLabelEncoder = LabelEncoder()
y = yLabelEncoder.fit_transform(y)

y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

<h3>Splitting the dataset into Training set and Test set</h3>

<h4>Dataset will be splitted into train and test sets, for model performance control</h4>

In [6]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.2, random_state = 0)
xTest

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04]])

<h3>Feature scalling</h3>

<h4>Data will be scalled so no variable dominates over the other while building models</h4>
<h4>Most common methods are standardiisation and normalisation</h4>

In [7]:
from sklearn.preprocessing import StandardScaler

xStandardScaler = StandardScaler()
xTrain = xStandardScaler.fit_transform(xTrain)
xTest = xStandardScaler.transform(xTest)
xTrain

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

<h3>Preprocessing template</h3>

<h4>Compiled steps for grab-and-go further in the course</h4>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dataFilePath = '../../data/Part 1 - Data Preprocessing/Data.csv'
dataset = pd.read_csv(dataFilePath)
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""xStandardScaler = StandardScaler()
xTrain = xStandardScaler.fit_transform(xTrain)
xTest = xStandardScaler.transform(xTest)"""